name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'  # Watch for changes only in the /frontend directory

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          path: frontend/slim-mom-app

      - name: Install, lint, build 🔧
        run: |
          npm install
          npm run lint:js
          npm run build
        working-directory: frontend/slim-mom-app

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
